---
# roles/compliance_checks/handlers/main.yml
# Handlers for restarting services after security changes.

- name: Restart SSH
  service:
    name: ssh
    state: restarted

- name: Restart auditd
  service:
    name: auditd
    state: restarted

- name: Initialize AIDE Database
  shell: aide --init
  args:
    creates: /var/lib/aide/aide.db.gz