AWSTemplateFormatVersion: '2010-09-09'
Description: "Creates a restricted IAM user with least privilege"

Resources:
  SecureIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: SecurityUser
      Policies:
        - PolicyName: LimitedS3ReadAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource: "*"